version: '3'

services:
  node1:
    build:
      context: .
    ports:
      - 8081:8081
  node2:
    build:
      context: .
    ports:
      - 8082:8082
  node3:
    build:
      context: .
    ports:
      - 8083:8083
  node4:
    build:
      context: .
    ports:
      - 8084:8084
