version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081-8084:8081-8084'
    networks:
      - tsp-network

  client1:
    build:
      context: .
      dockerfile: Dockerfile
    command: java Client 1 8081
    networks:
      - tsp-network

  client2:
    build:
      context: .
      dockerfile: Dockerfile
    command: java Client 2 8082
    networks:
      - tsp-network

  client3:
    build:
      context: .
      dockerfile: Dockerfile
    command: java Client 3 8083
    networks:
      - tsp-network

  client4:
    build:
      context: .
      dockerfile: Dockerfile
    command: java Client 4 8084
    networks:
      - tsp-network

networks:
  tsp-network:
